# Generated by Django 3.2.15 on 2022-12-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
