# Generated by Django 3.2.15 on 2022-12-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_data', '0002_alter_detail_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detail',
            table='Details',
        ),
    ]
