# Generated by Django 3.2.15 on 2022-12-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_data', '0003_alter_detail_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='time',
        ),
        migrations.AddField(
            model_name='detail',
            name='Date_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='Purpose',
            field=models.CharField(default=12, max_length=250),
            preserve_default=False,
        ),
    ]
